autenticacao/urls.py
from django import views
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

djangocinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', include('autenticacao.urls')),
    path('filme/', include('filme.urls')),
    path('sessao/', include('sessao.urls')),
    path('ingresso/', include('ingresso.urls')),
    path('sala/', include('sala.urls')),
]

filme/urls.py
from django.urls import path

from . import views

app_name = 'filme'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('cadastrar_request/', views.cadastrar_request, name='cadastrar_request'),
    path('cadastrar_via_request/', views.cadastrar_via_request, name='cadastrar_via_request'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

autenticacao/models.py
from django.db import models

# Create your models here.

autenticacao/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from .form import FormLogin

class Login(LoginView):
    form_class = FormLogin
    template_name = 'login.html'

autenticacao/templates/login.html
{% load static %}

<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Cinema</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>

<body>

<style>

  .content{
    background:rgb(91, 46, 102);
    margin: 0 auto;
    margin-top: 50px;
    width: 30%;
    padding: 50px;
    border: 1px solid #aaa;
    border-radius: 10px;
  }

  .btn-sucess{
    background-color: #fff;
    width: 100%;
  }

  .btn-sucess:hover{
    background-color: #fff;
  }

  h3{
    text-align: center;
    color: #fff;
    padding-bottom: 40px;
  }

  a{
    text-decoration: none;
  }

</style>

  <div class="content">
    
    <form action="{% url 'autenticacao:login' %}" method="post">

      <h3>Django Cinema</h3>

      {% csrf_token %}  
        
        {{ form.username }}
        {{ form.password }}

        <div class="row mb-4">
          <div class="col d-flex justify-content-center">
 
          
          </div>
    
        </div>
      
        <!-- Submit button -->
        <button type="submit" class="btn btn-sucess btn-block mb-4">Entrar</button>
      
        </div>
      </form>

  </div>

</body>

</html>