djangocinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', include('autenticacao.urls')),
    path('filme/', include('filme.urls')),
    path('sessao/', include('sessao.urls')),
    path('ingresso/', include('ingresso.urls')),
    path('sala/', include('sala.urls')),
]

filme/urls.py
from django.urls import path

from . import views

app_name = 'filme'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('cadastrar_request/', views.cadastrar_request, name='cadastrar_request'),
    path('cadastrar_via_request/', views.cadastrar_via_request, name='cadastrar_via_request'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

sessao/urls.py
from django.urls import path

from . import views

app_name = 'sessao'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

sessao/models.py
from django.db import models

from filme.models import Filme
from sala.models import Sala

class Sessao(models.Model):

    id_filme = models.ForeignKey(Filme, on_delete=models.CASCADE)

    atalho = models.SlugField('Atalho', null=False)

    num_sala = models.ForeignKey(Sala, on_delete=models.CASCADE)

    horario = models.TimeField('Horário')

    dt_sessao = models.DateField('Data do Sessao')

    valor_ingresso = models.FloatField('Valor Ingresso')

    criado_em = models.DateTimeField('Criado em', auto_now_add=True)

    def __str__(self):
        return str(self.id_filme)

    class Meta:

        verbose_name = 'Sessao'
        ordering = ['criado_em']

sessao/forms.py
from django import forms

from filme.models import Filme
from sala.models import Sala

class FormCadastrarSessao(forms.Form):

    #lista para escolha de filmes
    all_filmes = Filme.objects.all().values_list('id', 'titulo')
    filmes_choices = [('', '')]
    for i in all_filmes:
        filmes_choices.append(i)

    #lista para escolha de salas
    all_salas = Sala.objects.all().values_list('id', 'numero')
    salas_choices = [('', '')]
    for i in all_salas:
        salas_choices.append(i)

    id_filme = forms.ChoiceField(label='Escolha o filme para a Sessão', choices=filmes_choices, widget=forms.Select())
    num_sala = forms.ChoiceField(label='Escolha a Sala', choices=salas_choices, widget=forms.Select())
    horario = forms.TimeField(label='Horário')
    dt_sessao = forms.DateField(label='Data Sessão:')
    valor_ingresso = forms.FloatField(label='Valor do Ingresso')
    

sessao/views.py
import datetime
from django.shortcuts import get_object_or_404, render
from filme.models import Filme
from django.template.defaultfilters import slugify
from sala.models import Sala
from sessao.forms import FormCadastrarSessao
from django.contrib.auth.decorators import login_required

from sessao.models import Sessao

@login_required(login_url='autenticacao:login')
def index(request):

    sessoes = Sessao.objects.all().extra(
                select={'nome_da_imagem': 'filme_filme.nome_da_imagem'},
                tables=['sessao_sessao', 'filme_filme'],
                where=['sessao_sessao.id_filme_id=filme_filme.id']  
            )

    context = {
        'sessoes': sessoes,
    }

    return render(request, 'index_sessao.html', context)

@login_required(login_url='autenticacao:login')
def cadastrar(request):

    context = {}

    if request.method == 'POST':
        form = FormCadastrarSessao(request.POST)

        #verifica se o preenchimento do form foi válido
        if form.is_valid():
            context['is_valid'] = True
        
            #recebe os valores digitamos correspondente a cada campo do form

            id_filme = request.POST['id_filme']
            filme = Filme.objects.get(id=id_filme) #pega o nome do filme pelo ID
            num_sala = request.POST['num_sala'] 
            sala = Sala.objects.get(numero=num_sala) #pega o nome do filme pelo ID
            
            horario = request.POST['horario']
            dt_sessao = request.POST['dt_sessao']
            valor_ingresso = request.POST['valor_ingresso']

            #converte o nome do filme para slug (formato atalho)
            atalho = slugify(filme)
            
            #cadastra o filme
            cadastra_sessao = Sessao(id_filme=filme, atalho=atalho, num_sala=sala, horario=horario,
                                   dt_sessao=dt_sessao, valor_ingresso=valor_ingresso)
            cadastra_sessao.save()

            form = FormCadastrarSessao()
    else:
        form = FormCadastrarSessao()

    context['form'] = form

    return render(request, 'cadastrar_sessao.html', context)

@login_required(login_url='autenticacao:login')
def editar(request, id):

    sessao = get_object_or_404(Sessao,id=id)

    context = {}

    if request.method == 'POST':
        form = FormCadastrarSessao(request.POST)

        #verifica se o preenchimento do form foi válido
        if form.is_valid():
            context['is_valid'] = True
        
            #recebe os valores digitamos correspondente a cada campo do form
            id_filme = request.POST['id_filme']
            filme = Filme.objects.get(id=id_filme) #pega o nome do filme pelo ID
            num_sala = request.POST['num_sala'] 
            horario = request.POST['horario']
            dt_sessao = request.POST['dt_sessao']
            qtd_assentos_livres = request.POST['qtd_assentos_livres']
            valor_ingresso = request.POST['valor_ingresso']

            #converte o título para slug (formato atalho)
            atalho = slugify(filme)

            #cadastra o filme
            sessao_a_editar = Sessao.objects.filter(id=id)
            sessao_a_editar.update(id_filme=filme, atalho=atalho, num_sala=num_sala, horario=horario,
                                   dt_sessao=dt_sessao, qtd_assentos_livres=qtd_assentos_livres, valor_ingresso=valor_ingresso)

            form = FormCadastrarSessao()
    else:
        form = FormCadastrarSessao()

        form.initial['id_filme'] = sessao.id_filme
        form.initial['num_sala'] = sessao.num_sala
        form.initial['horario'] = sessao.horario
        form.initial['dt_sessao'] = sessao.dt_sessao.strftime('%Y-%m-%d')
        form.initial['qtd_assentos_livres'] = sessao.qtd_assentos_livres
        form.initial['valor_ingresso'] = sessao.valor_ingresso

    context['form'] = form
    context['id'] = id

    return render(request, 'editar_sessao.html', context)

@login_required(login_url='autenticacao:login')
def deletar(request, id):

    sessao = get_object_or_404(Sessao,id=id) 
    sessao.delete()

    return render(request, 'deletar_sessao.html')

sessao/templates/cadastrar_sessao.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}

<style>

    
    form {
        font-family: tahoma !important;
        display: block !important;
        margin: 0 auto !important;
        width: 60% !important;
        padding: 10px !important;
        border:0px solid #ccc !important;
    }

    label{
        color: #000 !important;
        font-size: 20px;
    }

    textarea{
        height: 100px;
        border: 0px solid #eed;
        border-bottom: 1px solid #aaa;
    }

    textarea:focus{
        outline: 0;
    }

    .btn-cadastrar{
        padding-top: 50px;
        text-align: center;
    }

    .card-panel{
        margin-bottom: 50px;
    }

    .alerta_sucesso {
        font-size: 15px;
        color: #3e881c;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

    .alerta_erros {
        font-size: 15px;
        color: #bd3918;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

</style>



<div class="container padding"> 

    {% if form.errors %}
        <div class="alerta_erros"><i class="fas fa-exclamation-triangle"></i>
            {{ form.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
		<div class="alerta_sucesso"><i class="far fa-check-circle"></i> 
			Sessao foi cadastrado com sucesso!
		</div>
	{% endif %}

    <div class="card-panel">
        <h5 class="center-align"><b>CADASTRAR SESSAO</b></h5>
    </div>
    <form action="{% url 'sessao:cadastrar' %}" method="post">
        {% csrf_token %}
        
        {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            </br>
        {% endfor %}
        
        <div class="btn-cadastrar">
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
    </form>
</div>

{% endblock %}

sessao/templates/deletar_sessao.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}

<div class="container padding">
    <div class="card-panel">
        <h5 class="center-align"><b>Sessão deletada com sucesso!</b></h5>
    </div>
</div>

{% endblock %}

sessao/templates/editar_sessao.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}

<style>

    
    form {
        font-family: tahoma !important;
        display: block !important;
        margin: 0 auto !important;
        width: 60% !important;
        padding: 10px !important;
        border:0px solid #ccc !important;
    }

    label{
        color: #000 !important;
        font-size: 20px;
    }

    textarea{
        height: 100px;
        border: 0px solid #eed;
        border-bottom: 1px solid #aaa;
    }

    textarea:focus{
        outline: 0;
    }

    .btn-cadastrar{
        padding-top: 50px;
        text-align: center;
    }

    .card-panel{
        margin-bottom: 50px;
    }

    .alerta_sucesso {
        font-size: 15px;
        color: #3e881c;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

    .alerta_erros {
        font-size: 15px;
        color: #bd3918;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

</style>

<div class="container padding"> 

    {% if form.errors %}
        <div class="alerta_erros"><i class="fas fa-exclamation-triangle"></i>
            {{ form.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
		<div class="alerta_sucesso"><i class="far fa-check-circle"></i> 
			Dados do Sessão foi alterado com sucesso!
		</div>
	{% endif %}

    <div class="card-panel">
        <h5 class="center-align"><b>EDITAR SESSAO</b></h5>
    </div>
    <form action="{% url 'sessao:editar' id %}" method="post">
        {% csrf_token %}
       
        {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            </br>
        {% endfor %}
       
        <div class="btn-cadastrar">
            <button type="submit" class="btn btn-primary">Editar</button>
        </div>
    </form>
</div>

{% endblock %}

sessao/templates/index_sessao.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}


<div class="container padding">

    <div id="nav_crud">

        <a href="{% url 'sessao:cadastrar' %}"><i class="fas fa-plus"></i> Cadastrar Sessão</a>
        
    </div>

    <div class="card-panel">
        <h5 class="center-align"><b>SESSAO</b></h5>
    </div>
    <div class="row">
        
        {% for sessao in sessoes %} 
                
                    <div class="col">
                        <div class="card">
                            <div id="nav_crud">
                                <a href="{% url 'sessao:editar' sessao.id %}"><i class="fas fa-edit"></i></a>
                                <a href="{% url 'sessao:deletar' sessao.id %}" onclick="return confirm('Deseja deletar este sessão?')"><i class="fas fa-trash-alt"></i></a>
                            </div>
                           
                            <div class="card-image">
                                <img src="{{ sessao.nome_da_imagem }}">
                                <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons"><i class="fas fa-chevron-circle-right"></i></i></a>
                            </div>
                            <div class="card-content">
                                <p>Sessão: <b>{{ sessao.id }}</b></p><br>
                                <p>Filme da Sessão: <b>{{ sessao.id_filme }}</b></p><br>
                                <p>SALA: <b>{{ sessao.num_sala }}</b></p><br>
                                <p>HORÁRIO: <b>{{ sessao.horario }}</b></p><br>
                                <p>DATA: <b>{{ sessao.dt_sessao }}</b></p><br>
                                <p>QTD. Assentos Disponíveis: <b>{{ sessao.qtd_assentos_livres }}</b></p><br>
                                <p>Valor do Ingresso: <b>{{ sessao.valor_ingresso }}</b></p><br>
                            </div>
                        </div>
                    </div>
          
        {% endfor %}
</div>
</div>

{% endblock %}