djangocinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', include('autenticacao.urls')),
    path('filme/', include('filme.urls')),
    path('sessao/', include('sessao.urls')),
    path('ingresso/', include('ingresso.urls')),
    path('sala/', include('sala.urls')),
]

filme/urls.py
from django.urls import path

from . import views

app_name = 'filme'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('cadastrar_request/', views.cadastrar_request, name='cadastrar_request'),
    path('cadastrar_via_request/', views.cadastrar_via_request, name='cadastrar_via_request'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

filme/models.py
from django.db import models
from django.contrib.auth.models import User

class Filme(models.Model):

    titulo = models.CharField('Título do Filme', max_length=255)

    atalho = models.SlugField('Atalho', null=False, unique=True)

    descricao = models.TextField('Descrição do Filme', blank=True)

    nome_da_imagem = models.CharField('Nome Img', max_length=100, unique=True)

    duracao = models.TextField('Duração do Filme')

    producao = models.CharField('Produção', max_length=255)

    direcao = models.CharField('Direção', max_length=255)

    esta_em_cartaz = models.BooleanField('Está em Cartaz', default=False)

    criado_em = models.DateTimeField('Criado em', auto_now_add=True)

    def __str__(self):
        return self.titulo

    class Meta:

        verbose_name = 'Filme'
        ordering = ['criado_em']

filme/forms.py
from django import forms


class FormCadastrar(forms.Form):

    titulo = forms.CharField(label='Título', widget=forms.TextInput())
    descricao = forms.CharField(label='Descrição', widget=forms.Textarea())
    nome_da_imagem = forms.CharField(label='Nome da Imagem', widget=forms.TextInput())
    duracao = forms.CharField(label='Duração', widget=forms.TextInput())
    producao = forms.CharField(label='Produção', widget=forms.TextInput())
    direcao = forms.CharField(label='Direção', widget=forms.TextInput())
    esta_em_cartaz = forms.BooleanField(required=False)

class FormPesquisar(forms.Form):

    pesquisar = forms.CharField(label='Pesquisar', widget=forms.TextInput(attrs={'class':'form-control me-2', 'placeholder': 'Pesquisar Filme'}))

filme/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.core import serializers
from shutil import make_archive
from filme.forms import FormCadastrar, FormPesquisar
from django.template.defaultfilters import slugify
import requests
import json

from filme.models import Filme

@login_required(login_url='autenticacao:login')
def index(request):

    filmes = Filme.objects.all()

    baixar_json(request)

    context = {
        'filmes': filmes
    }

    return render(request, 'index_filme.html', context)

@login_required(login_url='autenticacao:login')
def cadastrar_request(request):

    contextos = {}

    if request.method == 'POST':
        form = FormPesquisar(request.POST)

        if form.is_valid():

            contextos['is_valid'] = True

            titulo = request.POST['pesquisar']

            try:

                req = requests.get(f'http://www.omdbapi.com/?t={titulo}&apikey=7bb6880e')
                content = json.loads(req.text)
                contextos['titulo'] = content['Title']
                contextos['url_imagem'] = content['Poster']
                contextos['tipo'] = content['Type']
                contextos['descricao'] = content['Plot']
                contextos['duracao'] = content['Runtime']
                contextos['producao'] = content['Writer']
                contextos['direcao'] = content['Director']

                if content['Response']:
                    contextos['existe'] = True
                else:
                    contextos['existe'] = False
                        
            except:
                pass

    else:
        form = FormPesquisar()

    contextos['form'] = form

    return render(request, 'cadastrar_filme_request.html', contextos)

@login_required(login_url='autenticacao:login')
def cadastrar_via_request(request):

    contextos = {}

    titulo = request.GET.get('titulo')

    try:

        req = requests.get(f'http://www.omdbapi.com/?t={titulo}&apikey=7bb6880e')
        content = json.loads(req.text)
        contextos['titulo'] = content['Title']
        contextos['url_imagem'] = content['Poster']
        contextos['tipo'] = content['Type']
        contextos['descricao'] = content['Plot']
        contextos['duracao'] = content['Runtime']
        contextos['producao'] = content['Writer']
        contextos['direcao'] = content['Director']

        if content['Response']:
            contextos['existe'] = True
        else:
            contextos['existe'] = False
                   
    except:
        pass

    descricao = contextos['descricao']
    nome_da_imagem = contextos['url_imagem']
    duracao = contextos['duracao']
    producao = contextos['producao']     
    direcao = contextos['direcao']
    esta_em_cartaz = False
    atalho = slugify(titulo)

    contextos['cadastrado'] = True

    #cadastra o filme
    cadastra_filme = Filme(titulo=titulo, descricao=descricao, nome_da_imagem=nome_da_imagem,
                            duracao=duracao, producao=producao, direcao=direcao,
                            esta_em_cartaz=esta_em_cartaz, atalho=atalho)
    cadastra_filme.save()

    return render(request, 'cadastrar_filme_request.html', contextos)

@login_required(login_url='autenticacao:login')
def cadastrar(request):

    context = {}

    if request.method == 'POST':
        form = FormCadastrar(request.POST)

        #verifica se o preenchimento do form foi válido
        if form.is_valid():
            context['is_valid'] = True
        
            #recebe os valores digitamos correspondente a cada campo do form
            titulo = request.POST['titulo']
            descricao = request.POST['descricao'] 
            nome_da_imagem = request.POST['nome_da_imagem']
            duracao = request.POST['duracao']
            producao = request.POST['producao']
            direcao = request.POST['direcao']
            esta_em_cartaz = request.POST.get('esta_em_cartaz', False)

            #converte o valor do checkbox esta_em_cartaz para salvar no bd
            if esta_em_cartaz == 'on':
                esta_em_cartaz = True
            else:
                esta_em_cartaz = False

            #converte o título para slug (formato atalho)
            atalho = slugify(titulo)

            #cadastra o filme
            cadastra_filme = Filme(titulo=titulo, descricao=descricao, nome_da_imagem=nome_da_imagem,
                                duracao=duracao, producao=producao, direcao=direcao,
                                esta_em_cartaz=esta_em_cartaz, atalho=atalho)
            cadastra_filme.save()

            form = FormCadastrar()
    else:
        form = FormCadastrar()

    context['form'] = form

    return render(request, 'cadastrar_filme.html', context)

@login_required(login_url='autenticacao:login')
def editar(request, id):

    filme = get_object_or_404(Filme,id=id)

    context = {}

    if request.method == 'POST':
        form = FormCadastrar(request.POST)

        #verifica se o preenchimento do form foi válido
        if form.is_valid():
            context['is_valid'] = True
        
            #recebe os valores digitamos correspondente a cada campo do form
            titulo = request.POST['titulo']
            descricao = request.POST['descricao'] 
            nome_da_imagem = request.POST['nome_da_imagem']
            duracao = request.POST['duracao']
            producao = request.POST['producao']
            direcao = request.POST['direcao']
            esta_em_cartaz = request.POST.get('esta_em_cartaz', False)

            #converte o valor do checkbox esta_em_cartaz para salvar no bd
            if esta_em_cartaz == 'on':
                esta_em_cartaz = True
            else:
                esta_em_cartaz = False

            #converte o título para slug (formato atalho)
            atalho = slugify(titulo)

            #cadastra o filme
            filme_a_editar = Filme.objects.filter(id=id)
            filme_a_editar.update(titulo=titulo, descricao=descricao, nome_da_imagem=nome_da_imagem,
                                duracao=duracao, producao=producao, direcao=direcao,
                                esta_em_cartaz=esta_em_cartaz, atalho=atalho)

            form = FormCadastrar()
    else:
        form = FormCadastrar()

        form.initial['titulo'] = filme.titulo
        form.initial['descricao'] = filme.descricao
        form.initial['nome_da_imagem'] = filme.nome_da_imagem
        form.initial['duracao'] = filme.duracao
        form.initial['producao'] = filme.producao
        form.initial['direcao'] = filme.direcao
        form.initial['esta_em_cartaz'] = filme.esta_em_cartaz

    context['form'] = form
    context['id'] = id

    return render(request, 'editar_filme.html', context)

@login_required(login_url='autenticacao:login')
def deletar(request, id):

    filme = get_object_or_404(Filme,id=id) 
    filme.delete()

    return render(request, 'deletar_filme.html')

@login_required(login_url='autenticacao:login')
def baixar_json(request):

    dados = serializers.serialize("json", Filme.objects.all())

    f = open('static/json/filmes.json', 'w')
    json.dump(dados, f, sort_keys=True, indent=4)

    f.close()

    make_archive('static/json/', 'zip', 'static/json/')

filme/templates/cadastrar_filme.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}

<style>

    
    form {
        font-family: tahoma !important;
        display: block !important;
        margin: 0 auto !important;
        width: 60% !important;
        padding: 10px !important;
        border:0px solid #ccc !important;
    }

    label{
        color: #000 !important;
        font-size: 20px;
    }

    textarea{
        height: 100px;
        border: 0px solid #eed;
        border-bottom: 1px solid #aaa;
    }

    textarea:focus{
        outline: 0;
    }

    .btn-cadastrar{
        padding-top: 50px;
        text-align: center;
    }

    .card-panel{
        margin-bottom: 50px;
    }

    .alerta_sucesso {
        font-size: 15px;
        color: #3e881c;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

    .alerta_erros {
        font-size: 15px;
        color: #bd3918;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

</style>

<div class="container padding"> 

    {% if form.errors %}
        <div class="alerta_erros"><i class="fas fa-exclamation-triangle"></i>
            {{ form.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
		<div class="alerta_sucesso"><i class="far fa-check-circle"></i> 
			Filme foi cadastrado com sucesso!
		</div>
	{% endif %}

    <div class="card-panel">
        <h5 class="center-align"><b>CADASTRAR FILME</b></h5>
    </div>
    <form action="{% url 'filme:cadastrar' %}" method="post">
        {% csrf_token %}
       
        {{ form }} <span></span>
       
        <div class="btn-cadastrar">
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
    </form>
</div>

{% endblock %}

filme/templates/cadastrar_filme_request.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}

<style>

    .painel{
        display: grid;
        grid-template-columns: 70% 30%;
    }

    .card{
        text-align: center;
        padding: 20px 0;
    }
    
    form {
        font-family: tahoma !important;
        display: block !important;
        margin: 0 auto !important;
        width: 60% !important;
        padding: 10px !important;
        border:0px solid #ccc !important;
    }

    label{
        color: #000 !important;
        font-size: 20px;
    }

    textarea{
        height: 100px;
        border: 0px solid #eed;
        border-bottom: 1px solid #aaa;
    }

    textarea:focus{
        outline: 0;
    }

    .btn-cadastrar{
        padding-top: 50px;
        text-align: center;
    }

    .card-panel{
        margin-bottom: 50px;
    }

    .alerta_sucesso {
        font-size: 15px;
        color: #3e881c;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

    .alerta_erros {
        font-size: 15px;
        color: #bd3918;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

</style>

<div class="container padding"> 

    {% if form.errors %}
        <div class="alerta_erros"><i class="fas fa-exclamation-triangle"></i>
            {{ form.errors }}
        </div>
    {% endif %}

    <div class="card-panel">
        <h5 class="center-align"><b>CADASTRAR FILME</b></h5>
    </div>

    {% if cadastrado %}
        Filme cadastrado com sucesso!
        <style>
            .btn-cadastrar{
                visibility: hidden;
            }
        </style>
    {% endif %}


    <div class="painel">
        
        <form action="{% url 'filme:cadastrar_request' %}" method="post">
            {% csrf_token %}

            {{ form.pesquisar }}
        
            <div class="btn-cadastrar">
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </form>
        <div>

            {% if is_valid %}
                {% if existe %}
                    <div class="card" style="width: 12rem;">
                        <img src="{{ url_imagem }}" style="height: 300px;" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h4 class="card-title"> {{ titulo }}</h4>
                            <a href="{% url 'filme:cadastrar_via_request' %}?titulo={{ titulo }}" class="btn btn-primary"><i class="fas fa-plus"></i> Cadastrar</a>
                        </div>
                    </div>
                {% else %}
                    <p>Filme não encontrado!</p>
                {% endif %}
            {% endif %}

        </div>
    </div>
</div>

{% endblock %}

filme/templates/deletar_filme.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}

<div class="container padding">
    <div class="card-panel">
        <h5 class="center-align"><b>Filme deletado com sucesso!</b></h5>
    </div>
</div>

{% endblock %}

filme/templates/editar_filme.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}

<style>

    
    form {
        font-family: tahoma !important;
        display: block !important;
        margin: 0 auto !important;
        width: 60% !important;
        padding: 10px !important;
        border:0px solid #ccc !important;
    }

    label{
        color: #000 !important;
        font-size: 20px;
    }

    textarea{
        height: 100px;
        border: 0px solid #eed;
        border-bottom: 1px solid #aaa;
    }

    textarea:focus{
        outline: 0;
    }

    .btn-cadastrar{
        padding-top: 50px;
        text-align: center;
    }

    .card-panel{
        margin-bottom: 50px;
    }

    .alerta_sucesso {
        font-size: 15px;
        color: #3e881c;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

    .alerta_erros {
        font-size: 15px;
        color: #bd3918;
        padding: 7px;
        margin: 0 auto;
        text-align: center;
    }

</style>

<div class="container padding"> 

    {% if form.errors %}
        <div class="alerta_erros"><i class="fas fa-exclamation-triangle"></i>
            {{ form.errors }}
        </div>
    {% endif %}

    {% if is_valid %}
		<div class="alerta_sucesso"><i class="far fa-check-circle"></i> 
			Dados do Filme foi alterado com sucesso!
		</div>
	{% endif %}

    <div class="card-panel">
        <h5 class="center-align"><b>EDITAR FILME</b></h5>
    </div>
    <form action="{% url 'filme:editar' id %}" method="post">
        {% csrf_token %}
       
        {{ form }} <span></span>
       
        <div class="btn-cadastrar">
            <button type="submit" class="btn btn-primary">Editar</button>
        </div>
    </form>
</div>

{% endblock %}

filme/templates/index_filme.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Index{% endblock %}

{% block content %}

<style>

    .card{
        height: 650px;
    }

</style>

<div class="container padding">

    <div id="nav_crud">

        <a href="{% url 'filme:cadastrar' %}"><i class="fas fa-plus"></i> Cadastrar Manualmente</a>
        <a href="{% url 'filme:cadastrar_request' %}"><i class="fas fa-plus"></i> Cadastrar via Request</a>
        <a href="{% static 'json.zip' %}" download="filmes.zip"> Baixar JSON Filmes</a>
    </div>

    <div class="card-panel">
        <h5 class="center-align"><b>FILMES</b></h5>
    </div>
    <div class="row">

        {% for filme in filmes %}
            <div class="col">
                <div class="card">
                    <div id="nav_crud">
                        <a href="{% url 'filme:editar' filme.id %}"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'filme:deletar' filme.id %}" onclick="return confirm('Deseja deletar este filme?')"><i class="fas fa-trash-alt"></i></a>
                    </div>
                    <div class="card-image">
                        <img src="{{ filme.nome_da_imagem }}">
                        <a class="btn-floating halfway-fab waves-effect waves-light red"><i class="material-icons"><i class="fas fa-chevron-circle-right"></i></i></a>
                    </div>
                    <div class="card-content">
                        <p><b>{{ filme.titulo }}</b></p>
                        <br>

                        {% if filme.descricao|length > 100 %}
                            <p>{{ filme.descricao|truncatechars:100 }}</p>
                        {% else %}
                            <p>{{ filme.descricao }}</p>
                        {% endif %}

                    </div>
                </div>
            </div>
        {% endfor %}
</div>
</div>

{% endblock %}