autenticacao/urls.py
from django import views
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'autenticacao'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

djangocinema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', include('autenticacao.urls')),
    path('filme/', include('filme.urls')),
    path('sessao/', include('sessao.urls')),
    path('ingresso/', include('ingresso.urls')),
    path('sala/', include('sala.urls')),
]

filme/urls.py
from django.urls import path

from . import views

app_name = 'filme'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('cadastrar_request/', views.cadastrar_request, name='cadastrar_request'),
    path('cadastrar_via_request/', views.cadastrar_via_request, name='cadastrar_via_request'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

sessao/urls.py
from django.urls import path

from . import views

app_name = 'sessao'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('editar/<int:id>', views.editar, name='editar'),
    path('deletar/<int:id>', views.deletar, name='deletar')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from filme.models import Filme

@login_required(login_url='autenticacao:login')
def index(request):

    filmes_em_cartaz = Filme.objects.filter(esta_em_cartaz=True)

    context = {
        'filmes_em_cartaz': filmes_em_cartaz
    }

    return render(request, 'index.html', context)

@login_required(login_url='autenticacao:login')
def sobre(request):

    context = {
        'tema': 'Site de Cinema',
        'objetivo': 'Gerenciar um cinema, com opção para cadastro de filme, sessão e venda de ingressos',
        'desenvolvedores': 'Leandro e Claudivan'
    }

    return render(request, 'sobre.html', context)

main/templates/partials/footer.html
{% load static %}

<footer class="section">
    <div class="center grey-text">
        © Copyright 2021 Django Cinema - 
        <a href="/sobre/"> Entenda nosso Projeto - Sobre nós</a>
    </div>
</footer>

main/templates/partials/navbar.html
{% load static %}

<style>

        #logout{
          margin-left: 30px;
          list-style-type: none;
          color: #000;
        }

        #logout > a{
          text-decoration: none;
          padding-left: 10px;
          color: red;
          display: inline-block;
        }

</style>

<nav class="white z-depth-0"> 
    <div class="container">
        {% if user.get_username == 'admin-web' %}
            <a href="{% url 'main:index' %}" class="brand-logo brand-text left"><i class="fas fa-film"></i> DJCine</a>
            <ul id="nav-mobile" class="right hide-on-small-and-down">
                <li><a href="{% url 'filme:index' %}" class="btn brand z-depth-0">FILMES</a></li>
                <li><a href="{% url 'sessao:index' %}" class="btn brand z-depth-0">SESSÕES</a></li>
                <li><a href="{% url 'ingresso:index' %}" class="btn brand z-depth-0">INGRESSO</a></li>
                <li><a class="btn brand z-depth-0" href="/admin/">Admin <i class="fa-solid fa-gear"></i></a></li>
                <li id="logout" class="nav-item p-3">
                    <span>Olá, <b style="color:rgb(58, 12, 70);">{{ user.get_username }}</b></span>  <a href="{% url 'autenticacao:logout' %}"> Sair</a>
                </li>
            </ul>
                
        {% else %}

            <a href="{% url 'main:index' %}" class="brand-logo brand-text left"><i class="fas fa-film"></i> DJCine</a>
            <ul id="nav-mobile" class="right hide-on-small-and-down">
                <li><a href="{% url 'ingresso:index' %}" class="btn brand z-depth-0">INGRESSO</a></li>
                <li id="logout" class="nav-item p-3">
                    <span>Olá, <b style="color:rgb(58, 12, 70);">{{ user.get_username }}</b></span>  <a href="{% url 'autenticacao:logout' %}"> Sair</a>
                </li>
            </ul>    

        {% endif %}
        
    </div>
</nav>